#!/usr/bin/env bash

# This script runs inside cli. See https://docs.docksal.io/fin/custom-commands/#target_cli
#: exec_target = cli

## Test site installation
##
## Usage: fin test

# Abort if anything fails
set -eux

echo "Testing home page..."
curl -sL -I http://${VIRTUAL_HOST} | grep "HTTP/1.1 200 OK"
curl -sL http://${VIRTUAL_HOST} | grep "My Drupal 7 Site"
echo "Testing login page..."
curl -sL -I http://${VIRTUAL_HOST}/user/login | grep "HTTP/1.1 200 OK"

echo "Testing multisite..."
curl -sL -I http://anothersite.${VIRTUAL_HOST} | grep "HTTP/1.1 200 OK"
curl -sL http://anothersite.${VIRTUAL_HOST} | grep "Another Drupal 7 Site"
